### ISSUE TITLE
Probleminha com a documentação

### ISSUE THREAD

**Issue by andrearruda82** [fgsl/LaminasUser#3]
Ao seguir a documentação para instalação via composer:

```
"require": {  
    "fgsl/laminas-user": "^3.0"  
}  
```
Retorna a seguinte mensagem:

> Your requirements could not be resolved to an installable set of packages.
>  Problem 1
>    - The requested package fgsl/laminas-user ^3.0 exists as fgsl/laminas-user[0.1.0, 0.2.0, dev-master, 0.1.x-dev] but these are rejected by your constraint.

`composer require fgsl/laminas-user` resolvi assim! 👍 

Uma dúvida ante p/ utilizar ZfcUser c/ Doctrine utilizava ZfcUserDoctrineORM, esse outro pacote será atualizado?

Obrigado, ótima iniciativa a conversão!

**Comment by fgsl** [comment]
Fixed by commit: https://github.com/fgsl/LaminasUser/commit/05870f83c4a71cdd0cd4df3a60ad148c71c74987

**Comment by fgsl** [comment]
> Uma dúvida ante p/ utilizar ZfcUser c/ Doctrine utilizava ZfcUserDoctrineORM, esse outro pacote será atualizado?
@andrearruda , eu fiz esta migração pra atender a um projeto feito com ZF2, com o objetivo de manter ele funcionando e usar Laminas/Db. Não pretendo investir na integração com Doctrine. Mas fique à vontade para alterar.
